app: 
  eureka-server: discovery-server
  mongo: mongo
server:
  port: 8086

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: ${app.mongo}
      port: 27017
      database: application

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka