server:
  port: 8083

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: mongo
      port: 27017
      database: post

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka