server:
  port: 8085

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: localhost
      port: 27017
      database: resume

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health, gateway, prometheus
