server:
  port: 8088

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: localhost
      port: 27017
      database: notification
      
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/