app: 
  eureka-server: discovery-server
  mongo: mongo
  mail: maildev

server:
  port: 8088

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: ${app.mongo}
      port: 27017
      database: notification
      
  mail:
    host: ${app.mail}
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka-server}:8761/eureka/