server:
  port: 8087
  
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      host: localhost
      port: 27017
      database: wishlist

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/